jwt:
  secret-key: CLAP-PAUSE-SERVER-MEMBER-SECRET-KEY
  expired-time: 8640000
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
